language: php

php:
  - 5.5
  - 5.6
  - 7.0

# faster builds on new travis setup not using sudo
sudo: false

addons:
    code_climate:
        repo_token: 15fc2719c61e206664fe063819d9d5209d74000ee90d9f66c3512a85b5db5cd1

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction --dev

script:
  - phpunit --coverage-clover build/logs/clover.xml --configuration ./phpunit.xml.dist ./tests

after_script:
  - vendor/bin/test-reporter